# Auto-generated from NSE India constituent lists (archives.nseindia.com)
# Last updated: 2026-06-29

INDICES = {
    "NIFTY 50": [
        "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV",
        "BEL", "BHARTIARTL", "CIPLA", "COALINDIA", "DRREDDY", "EICHERMOT", "ETERNAL", "GRASIM",
        "HCLTECH", "HDFCBANK", "HDFCLIFE", "HINDALCO", "HINDUNILVR", "ICICIBANK", "ITC", "INFY",
        "INDIGO", "JSWSTEEL", "JIOFIN", "KOTAKBANK", "LT", "M&M", "MARUTI", "MAXHEALTH",
        "NTPC", "NESTLEIND", "ONGC", "POWERGRID", "RELIANCE", "SBILIFE", "SHRIRAMFIN", "SBIN",
        "SUNPHARMA", "TCS", "TATACONSUM", "TMPV", "TATASTEEL", "TECHM", "TITAN", "TRENT",
        "ULTRACEMCO", "WIPRO",
    ],

    "NIFTY NEXT 50": [
        "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "DMART", "BAJAJHLDNG", "BANKBARODA",
        "BPCL", "BOSCHLTD", "BRITANNIA", "CGPOWER", "CANBK", "CHOLAFIN", "CUMMINSIND", "DLF",
        "DIVISLAB", "GAIL", "GODREJCP", "HDFCAMC", "HAL", "HINDZINC", "HYUNDAI", "INDHOTEL",
        "IOC", "IRFC", "JINDALSTEL", "LTM", "LODHA", "MAZDOCK", "MUTHOOTFIN", "PIDILITIND",
        "PFC", "PNB", "RECLTD", "MOTHERSON", "SHREECEM", "ENRIN", "SIEMENS", "SOLARINDS",
        "TVSMOTOR", "TATACAP", "TMCV", "TATAPOWER", "TORNTPHARM", "UNIONBANK", "UNITDSPR", "VBL",
        "VEDL", "ZYDUSLIFE",
    ],

    "NIFTY MIDCAP 150": [
        "360ONE", "3MINDIA", "ACC", "AIAENG", "APLAPOLLO", "AUBANK", "AWL", "ABBOTINDIA",
        "ATGL", "ABCAPITAL", "AJANTPHARM", "ALKEM", "ANTHEM", "APARINDS", "APOLLOTYRE", "ASHOKLEY",
        "ASTRAL", "AUROPHARMA", "AIIL", "BSE", "BAJAJHFL", "BALKRISIND", "BANKINDIA", "MAHABANK",
        "BERGEPAINT", "BDL", "BHARATFORG", "BHEL", "BHARTIHEXA", "GROWW", "BIOCON", "BLUESTARCO",
        "CRISIL", "COCHINSHIP", "COFORGE", "COLPAL", "CONCOR", "COROMANDEL", "DABUR", "DALBHARAT",
        "DIXON", "ENDURANCE", "ESCORTS", "EXIDEIND", "NYKAA", "FEDERALBNK", "FORTIS", "GVT&D",
        "GMRAIRPORT", "GICRE", "GLAXO", "GLENMARK", "MEDANTA", "GODFRYPHLP", "GODREJIND", "GODREJPROP",
        "FLUOROCHEM", "HDBFS", "HAVELLS", "HEROMOTOCO", "HEXT", "HINDPETRO", "POWERINDIA", "HONAUT",
        "HUDCO", "ICICIGI", "ICICIAMC", "ICICIPRULI", "IDFCFIRSTB", "ITCHOTELS", "INDIANB", "IRCTC",
        "IREDA", "INDUSTOWER", "INDUSINDBK", "NAUKRI", "IPCALAB", "JKCEMENT", "JSWENERGY", "JSWINFRA",
        "JSL", "JUBLFOOD", "KPRMILL", "KEI", "KPITTECH", "KALYANKJIL", "LTF", "LTTS",
        "LGEINDIA", "LICHSGFIN", "LAURUSLABS", "LENSKART", "LICI", "LINDEINDIA", "LLOYDSME", "LUPIN",
        "MRF", "M&MFIN", "MANKIND", "MARICO", "MFSL", "MOTILALOFS", "MPHASIS", "MCX",
        "NHPC", "NLCINDIA", "NMDC", "NTPCGREEN", "NATIONALUM", "NAM-INDIA", "OBEROIRLTY", "OIL",
        "PAYTM", "OFSS", "POLICYBZR", "PIIND", "PAGEIND", "PATANJALI", "PERSISTENT", "PETRONET",
        "PHOENIXLTD", "POLYCAB", "PREMIERENE", "PRESTIGE", "RADICO", "RVNL", "SBICARD", "SJVN",
        "SRF", "SCHAEFFLER", "SAIL", "SUNDARMFIN", "SUPREMEIND", "SUZLON", "SWIGGY", "TATACOMM",
        "TATAELXSI", "TATAINVEST", "NIACL", "THERMAX", "TORNTPOWER", "TIINDIA", "UNOMINDA", "UPL",
        "UBL", "VMM", "IDEA", "VOLTAS", "WAAREEENER", "YESBANK",
    ],

    "NIFTY SMALLCAP 250": [
        "ACMESOLAR", "AADHARHFC", "AARTIIND", "AAVAS", "ACE", "ACUTAAS", "ABFRL", "ABLBL",
        "ABREL", "ABSLAMC", "CPPLUS", "AEGISLOG", "AEGISVOPAK", "AFCONS", "AFFLE", "ABDL",
        "ARE&M", "AMBER", "ANANDRATHI", "ANANTRAJ", "ANGELONE", "ANURAS", "APTUS", "ASAHIINDIA",
        "ASTERDM", "ATHERENERG", "ATUL", "BEML", "BLS", "BALRAMCHIN", "BANDHANBNK", "BATAINDIA",
        "BAYERCROP", "BELRISE", "BIKAJI", "BSOFT", "BLUEDART", "BLUEJET", "BBTC", "FIRSTCRY",
        "BRIGADE", "MAPMYINDIA", "CCL", "CESC", "CIEINDIA", "CANFINHOME", "CANHLIFE", "CAPLIPOINT",
        "CGCL", "CARBORUNIV", "CARTRADE", "CASTROLIND", "CEATLTD", "CEMPRO", "CENTRALBK", "CDSL",
        "CHALET", "CHAMBLFERT", "CHENNPETRO", "CHOICEIN", "CHOLAHLDNG", "CUB", "CLEAN", "COHANCE",
        "CAMS", "CONCORDBIO", "CRAFTSMAN", "CREDITACC", "CROMPTON", "CYIENT", "DCMSHRIRAM", "DOMS",
        "DATAPATTNS", "DEEPAKFERT", "DEEPAKNTR", "DELHIVERY", "DEVYANI", "LALPATHLAB", "EIDPARRY", "EIHOTEL",
        "ELECON", "ELGIEQUIP", "EMAMILTD", "EMCURE", "EMMVEE", "ENGINERSIN", "ERIS", "FACT",
        "FINCABLES", "FSL", "FIVESTAR", "FORCEMOT", "GABRIEL", "GALLANTT", "GRSE", "GILLETTE",
        "GLAND", "GODIGIT", "GPIL", "GRANULES", "GRAPHITE", "GRAVITA", "GESHIP", "GMDCLTD",
        "HEG", "HBLENGINE", "HFCL", "HSCL", "HINDCOPPER", "HOMEFIRST", "HONASA", "IDBI",
        "IFCI", "IIFL", "IRB", "IRCON", "ITI", "INDGN", "INDIACEM", "INDIAMART",
        "IEX", "IOB", "IGL", "INOXWIND", "INTELLECT", "IGIL", "IKS", "JBCHEPHARM",
        "JBMA", "JKTYRE", "JMFINANCIL", "JSWCEMENT", "JSWDULUX", "JAINREC", "JPPOWER", "J&KBANK",
        "JINDALSAW", "JUBLINGREA", "JUBLPHARMA", "JWL", "JYOTICNC", "KAJARIACER", "KPIL", "KARURVYSYA",
        "KAYNES", "KEC", "KFINTECH", "KIRLOSENG", "KIMS", "LTFOODS", "LATENTVIEW", "THELEELA",
        "LEMONTREE", "MMTC", "MGL", "MANAPPURAM", "MRPL", "MEESHO", "MINDACORP", "MSUMI",
        "NATCOPHARM", "NBCC", "NCC", "NSLNISP", "NH", "NAVA", "NAVINFLUOR", "NETWEB",
        "NEULANDLAB", "NEWGEN", "NIVABUPA", "NUVAMA", "NUVOCO", "OLAELEC", "OLECTRA", "ONESOURCE",
        "PCBL", "PGEL", "PNBHOUSING", "PTCIL", "PVRINOX", "PARADEEP", "PFIZER", "PWL",
        "PINELABS", "PIRAMALFIN", "PPLPHARMA", "POLYMED", "POONAWALLA", "RRKABEL", "RBLBANK", "RHIM",
        "RITES", "RAILTEL", "RAINBOW", "RKFORGE", "REDINGTON", "RPOWER", "SBFC", "SAGILITY",
        "SAILIFE", "SAMMAANCAP", "SAPPHIRE", "SARDAEN", "SAREGAMA", "SCHNEIDER", "SCI", "SHYAMMETL",
        "SIGNATURE", "SOBHA", "SONACOMS", "SONATSOFTW", "STARHEALTH", "SUMICHEM", "SUNTV", "SPLPETRO",
        "SWANCORP", "SYNGENE", "SYRMA", "TBOTEK", "TATACHEM", "TATATECH", "TTML", "TECHNOE",
        "TEGA", "TEJASNET", "TENNIND", "RAMCOCEM", "TIMKEN", "TITAGARH", "TARIL", "TRAVELFOOD",
        "TRIDENT", "TRITURBINE", "UCOBANK", "UTIAMC", "URBANCO", "USHAMART", "VTL", "VIJAYA",
        "WELCORP", "WELSPUNLIV", "WHIRLPOOL", "WOCKPHARMA", "ZFCVINDIA", "ZEEL", "ZENTEC", "ZENSARTECH",
        "ZYDUSWELL", "ECLERX",
    ],

    "NIFTY BANK": [
        "AUBANK", "AXISBANK", "BANKBARODA", "CANBK", "FEDERALBNK", "HDFCBANK", "ICICIBANK", "IDFCFIRSTB",
        "INDUSINDBK", "KOTAKBANK", "PNB", "SBIN", "UNIONBANK", "YESBANK",
    ],

    "NIFTY IT": [
        "COFORGE", "HCLTECH", "INFY", "LTM", "MPHASIS", "OFSS", "PERSISTENT", "TCS",
        "TECHM", "WIPRO",
    ],

    "NIFTY AUTO": [
        "ASHOKLEY", "BAJAJ-AUTO", "BHARATFORG", "BOSCHLTD", "EICHERMOT", "EXIDEIND", "HEROMOTOCO", "M&M",
        "MARUTI", "MOTHERSON", "SONACOMS", "TVSMOTOR", "TMPV", "TIINDIA", "UNOMINDA",
    ],

    "NIFTY PHARMA": [
        "ABBOTINDIA", "AJANTPHARM", "ALKEM", "AUROPHARMA", "BIOCON", "CIPLA", "DIVISLAB", "DRREDDY",
        "GLAND", "GLENMARK", "IPCALAB", "JBCHEPHARM", "LAURUSLABS", "LUPIN", "MANKIND", "PPLPHARMA",
        "SUNPHARMA", "TORNTPHARM", "WOCKPHARMA", "ZYDUSLIFE",
    ],

    "NIFTY FMCG": [
        "BRITANNIA", "COLPAL", "DABUR", "EMAMILTD", "GODREJCP", "HINDUNILVR", "ITC", "MARICO",
        "NESTLEIND", "PATANJALI", "RADICO", "TATACONSUM", "UBL", "UNITDSPR", "VBL",
    ],

    "NIFTY METAL": [
        "APLAPOLLO", "ADANIENT", "HINDALCO", "HINDCOPPER", "HINDZINC", "JSWSTEEL", "JSL", "JINDALSTEL",
        "LLOYDSME", "NMDC", "NATIONALUM", "SAIL", "TATASTEEL", "VEDL", "WELCORP",
    ],

    "NIFTY ENERGY": [
        "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "ATGL", "AEGISLOG", "BHEL", "BPCL",
        "CESC", "CGPOWER", "CASTROLIND", "COALINDIA", "GAIL", "GVT&D", "HINDPETRO", "POWERINDIA",
        "IOC", "IGL", "INOXWIND", "JSWENERGY", "JPPOWER", "MGL", "NHPC", "NLCINDIA",
        "NTPCGREEN", "NTPC", "NAVA", "ONGC", "OIL", "PETRONET", "POWERGRID", "RELIANCE",
        "RPOWER", "SJVN", "ENRIN", "SIEMENS", "SUZLON", "TATAPOWER", "THERMAX", "TORNTPOWER",
    ],

    "NIFTY REALTY": [
        "ABREL", "ANANTRAJ", "BRIGADE", "DLF", "GODREJPROP", "LODHA", "OBEROIRLTY", "PHOENIXLTD",
        "PRESTIGE", "SOBHA",
    ],

}

# Derived indices
INDICES["NIFTY 100"] = list(dict.fromkeys(
    INDICES["NIFTY 50"] + INDICES["NIFTY NEXT 50"]
))

INDICES["NIFTY 200"] = list(dict.fromkeys(
    INDICES["NIFTY 100"] + INDICES["NIFTY MIDCAP 150"]
))

# NIFTY 500 — official NSE list (500 stocks, sourced directly from NSE India)
INDICES["NIFTY 500"] = [
        "360ONE", "3MINDIA", "ABB", "ACC", "ACMESOLAR", "AIAENG", "APLAPOLLO", "AUBANK",
        "AWL", "AADHARHFC", "AARTIIND", "AAVAS", "ABBOTINDIA", "ACE", "ACUTAAS", "ADANIENSOL",
        "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "ATGL", "ABCAPITAL", "ABFRL", "ABLBL",
        "ABREL", "ABSLAMC", "CPPLUS", "AEGISLOG", "AEGISVOPAK", "AFCONS", "AFFLE", "AJANTPHARM",
        "ALKEM", "ABDL", "ARE&M", "AMBER", "AMBUJACEM", "ANANDRATHI", "ANANTRAJ", "ANGELONE",
        "ANTHEM", "ANURAS", "APARINDS", "APOLLOHOSP", "APOLLOTYRE", "APTUS", "ASAHIINDIA", "ASHOKLEY",
        "ASIANPAINT", "ASTERDM", "ASTRAL", "ATHERENERG", "ATUL", "AUROPHARMA", "AIIL", "DMART",
        "AXISBANK", "BEML", "BLS", "BSE", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BAJAJHLDNG",
        "BAJAJHFL", "BALKRISIND", "BALRAMCHIN", "BANDHANBNK", "BANKBARODA", "BANKINDIA", "MAHABANK", "BATAINDIA",
        "BAYERCROP", "BELRISE", "BERGEPAINT", "BDL", "BEL", "BHARATFORG", "BHEL", "BPCL",
        "BHARTIARTL", "BHARTIHEXA", "BIKAJI", "GROWW", "BIOCON", "BSOFT", "BLUEDART", "BLUEJET",
        "BLUESTARCO", "BBTC", "BOSCHLTD", "FIRSTCRY", "BRIGADE", "BRITANNIA", "MAPMYINDIA", "CCL",
        "CESC", "CGPOWER", "CIEINDIA", "CRISIL", "CANFINHOME", "CANBK", "CANHLIFE", "CAPLIPOINT",
        "CGCL", "CARBORUNIV", "CARTRADE", "CASTROLIND", "CEATLTD", "CEMPRO", "CENTRALBK", "CDSL",
        "CHALET", "CHAMBLFERT", "CHENNPETRO", "CHOICEIN", "CHOLAHLDNG", "CHOLAFIN", "CIPLA", "CUB",
        "CLEAN", "COALINDIA", "COCHINSHIP", "COFORGE", "COHANCE", "COLPAL", "CAMS", "CONCORDBIO",
        "CONCOR", "COROMANDEL", "CRAFTSMAN", "CREDITACC", "CROMPTON", "CUMMINSIND", "CYIENT", "DCMSHRIRAM",
        "DLF", "DOMS", "DABUR", "DALBHARAT", "DATAPATTNS", "DEEPAKFERT", "DEEPAKNTR", "DELHIVERY",
        "DEVYANI", "DIVISLAB", "DIXON", "LALPATHLAB", "DRREDDY", "EIDPARRY", "EIHOTEL", "EICHERMOT",
        "ELECON", "ELGIEQUIP", "EMAMILTD", "EMCURE", "EMMVEE", "ENDURANCE", "ENGINERSIN", "ERIS",
        "ESCORTS", "ETERNAL", "EXIDEIND", "NYKAA", "FEDERALBNK", "FACT", "FINCABLES", "FSL",
        "FIVESTAR", "FORCEMOT", "FORTIS", "GAIL", "GVT&D", "GMRAIRPORT", "GABRIEL", "GALLANTT",
        "GRSE", "GICRE", "GILLETTE", "GLAND", "GLAXO", "GLENMARK", "MEDANTA", "GODIGIT",
        "GPIL", "GODFRYPHLP", "GODREJCP", "GODREJIND", "GODREJPROP", "GRANULES", "GRAPHITE", "GRASIM",
        "GRAVITA", "GESHIP", "FLUOROCHEM", "GMDCLTD", "HEG", "HBLENGINE", "HCLTECH", "HDBFS",
        "HDFCAMC", "HDFCBANK", "HDFCLIFE", "HFCL", "HAVELLS", "HEROMOTOCO", "HEXT", "HSCL",
        "HINDALCO", "HAL", "HINDCOPPER", "HINDPETRO", "HINDUNILVR", "HINDZINC", "POWERINDIA", "HOMEFIRST",
        "HONASA", "HONAUT", "HUDCO", "HYUNDAI", "ICICIBANK", "ICICIGI", "ICICIAMC", "ICICIPRULI",
        "IDBI", "IDFCFIRSTB", "IFCI", "IIFL", "IRB", "IRCON", "ITCHOTELS", "ITC",
        "ITI", "INDGN", "INDIACEM", "INDIAMART", "INDIANB", "IEX", "INDHOTEL", "IOC",
        "IOB", "IRCTC", "IRFC", "IREDA", "IGL", "INDUSTOWER", "INDUSINDBK", "NAUKRI",
        "INFY", "INOXWIND", "INTELLECT", "INDIGO", "IGIL", "IKS", "IPCALAB", "JBCHEPHARM",
        "JKCEMENT", "JBMA", "JKTYRE", "JMFINANCIL", "JSWCEMENT", "JSWDULUX", "JSWENERGY", "JSWINFRA",
        "JSWSTEEL", "JAINREC", "JPPOWER", "J&KBANK", "JINDALSAW", "JSL", "JINDALSTEL", "JIOFIN",
        "JUBLFOOD", "JUBLINGREA", "JUBLPHARMA", "JWL", "JYOTICNC", "KPRMILL", "KEI", "KPITTECH",
        "KAJARIACER", "KPIL", "KALYANKJIL", "KARURVYSYA", "KAYNES", "KEC", "KFINTECH", "KIRLOSENG",
        "KOTAKBANK", "KIMS", "LTF", "LTTS", "LGEINDIA", "LICHSGFIN", "LTFOODS", "LTM",
        "LT", "LATENTVIEW", "LAURUSLABS", "THELEELA", "LEMONTREE", "LENSKART", "LICI", "LINDEINDIA",
        "LLOYDSME", "LODHA", "LUPIN", "MMTC", "MRF", "MGL", "M&MFIN", "M&M",
        "MANAPPURAM", "MRPL", "MANKIND", "MARICO", "MARUTI", "MFSL", "MAXHEALTH", "MAZDOCK",
        "MEESHO", "MINDACORP", "MSUMI", "MOTILALOFS", "MPHASIS", "MCX", "MUTHOOTFIN", "NATCOPHARM",
        "NBCC", "NCC", "NHPC", "NLCINDIA", "NMDC", "NSLNISP", "NTPCGREEN", "NTPC",
        "NH", "NATIONALUM", "NAVA", "NAVINFLUOR", "NESTLEIND", "NETWEB", "NEULANDLAB", "NEWGEN",
        "NAM-INDIA", "NIVABUPA", "NUVAMA", "NUVOCO", "OBEROIRLTY", "ONGC", "OIL", "OLAELEC",
        "OLECTRA", "PAYTM", "ONESOURCE", "OFSS", "POLICYBZR", "PCBL", "PGEL", "PIIND",
        "PNBHOUSING", "PTCIL", "PVRINOX", "PAGEIND", "PARADEEP", "PATANJALI", "PERSISTENT", "PETRONET",
        "PFIZER", "PHOENIXLTD", "PWL", "PIDILITIND", "PINELABS", "PIRAMALFIN", "PPLPHARMA", "POLYMED",
        "POLYCAB", "POONAWALLA", "PFC", "POWERGRID", "PREMIERENE", "PRESTIGE", "PNB", "RRKABEL",
        "RBLBANK", "RECLTD", "RHIM", "RITES", "RADICO", "RVNL", "RAILTEL", "RAINBOW",
        "RKFORGE", "REDINGTON", "RELIANCE", "RPOWER", "SBFC", "SBICARD", "SBILIFE", "SJVN",
        "SRF", "SAGILITY", "SAILIFE", "SAMMAANCAP", "MOTHERSON", "SAPPHIRE", "SARDAEN", "SAREGAMA",
        "SCHAEFFLER", "SCHNEIDER", "SCI", "SHREECEM", "SHRIRAMFIN", "SHYAMMETL", "ENRIN", "SIEMENS",
        "SIGNATURE", "SOBHA", "SOLARINDS", "SONACOMS", "SONATSOFTW", "STARHEALTH", "SBIN", "SAIL",
        "SUMICHEM", "SUNPHARMA", "SUNTV", "SUNDARMFIN", "SUPREMEIND", "SPLPETRO", "SUZLON", "SWANCORP",
        "SWIGGY", "SYNGENE", "SYRMA", "TBOTEK", "TVSMOTOR", "TATACAP", "TATACHEM", "TATACOMM",
        "TCS", "TATACONSUM", "TATAELXSI", "TATAINVEST", "TMCV", "TMPV", "TATAPOWER", "TATASTEEL",
        "TATATECH", "TTML", "TECHM", "TECHNOE", "TEGA", "TEJASNET", "TENNIND", "NIACL",
        "RAMCOCEM", "THERMAX", "TIMKEN", "TITAGARH", "TITAN", "TORNTPHARM", "TORNTPOWER", "TARIL",
        "TRAVELFOOD", "TRENT", "TRIDENT", "TRITURBINE", "TIINDIA", "UCOBANK", "UNOMINDA", "UPL",
        "UTIAMC", "ULTRACEMCO", "UNIONBANK", "UBL", "UNITDSPR", "URBANCO", "USHAMART", "VTL",
        "VBL", "VEDL", "VIJAYA", "VMM", "IDEA", "VOLTAS", "WAAREEENER", "WELCORP",
        "WELSPUNLIV", "WHIRLPOOL", "WIPRO", "WOCKPHARMA", "YESBANK", "ZFCVINDIA", "ZEEL", "ZENTEC",
        "ZENSARTECH", "ZYDUSLIFE", "ZYDUSWELL", "ECLERX",
]

# All NSE Stocks = full NIFTY 500 universe
INDICES["All NSE Stocks"] = INDICES["NIFTY 500"]


# NSE F&O (Futures & Options) eligible stocks
INDICES["NSE F&O"] = list(dict.fromkeys([
    # NIFTY 50
    "ADANIENT","ADANIPORTS","APOLLOHOSP","ASIANPAINT","AXISBANK","BAJAJ-AUTO","BAJFINANCE",
    "BAJAJFINSV","BEL","BHARTIARTL","CIPLA","COALINDIA","DRREDDY","EICHERMOT","ETERNAL",
    "GRASIM","HCLTECH","HDFCBANK","HDFCLIFE","HINDALCO","HINDUNILVR","ICICIBANK","ITC",
    "INFY","INDIGO","JSWSTEEL","KOTAKBANK","LT","M&M","MARUTI","NTPC","NESTLEIND","ONGC",
    "POWERGRID","RELIANCE","SBILIFE","SHRIRAMFIN","SBIN","SUNPHARMA","TCS","TATACONSUM",
    "TMPV","TATASTEEL","TECHM","TITAN","TRENT","ULTRACEMCO","WIPRO",
    # NIFTY NEXT 50
    "ABB","ADANIENSOL","ADANIGREEN","ADANIPOWER","AMBUJACEM","DMART","BANKBARODA","BPCL",
    "BOSCHLTD","BRITANNIA","CGPOWER","CANBK","CHOLAFIN","CUMMINSIND","DLF","DIVISLAB",
    "GAIL","GODREJCP","HDFCAMC","HAL","INDHOTEL","IOC","IRFC","JINDALSTEL","LODHA",
    "MUTHOOTFIN","PIDILITIND","PFC","PNB","RECLTD","MOTHERSON","SIEMENS","TVSMOTOR",
    "TATACAP","TATAPOWER","TORNTPHARM","UNIONBANK","UNITDSPR","VBL","VEDL","ZYDUSLIFE",
    # Midcap F&O eligible
    "ACC","AUBANK","ABBOTINDIA","AJANTPHARM","ALKEM","APOLLOTYRE","ASHOKLEY","ASTRAL",
    "AUROPHARMA","BALKRISIND","BANKINDIA","BERGEPAINT","BHARATFORG","BHEL","BIOCON",
    "COFORGE","COLPAL","CONCOR","DABUR","DIXON","ESCORTS","EXIDEIND","FEDERALBNK",
    "GMRAIRPORT","GICRE","GLENMARK","GODREJPROP","HAVELLS","HEROMOTOCO","HINDPETRO",
    "ICICIGI","ICICIPRULI","IDFCFIRSTB","IRCTC","INDUSTOWER","INDUSINDBK","NAUKRI",
    "IPCALAB","JKCEMENT","JSWENERGY","JUBLFOOD","KPITTECH","KALYANKJIL","LTTS",
    "LICHSGFIN","LAURUSLABS","LUPIN","MRF","M&MFIN","MANKIND","MARICO","MPHASIS","MCX",
    "NHPC","NMDC","NATIONALUM","OBEROIRLTY","OFSS","PIIND","PERSISTENT","PETRONET",
    "PHOENIXLTD","POLYCAB","PRESTIGE","SBICARD","SRF","SAIL","SUPREMEIND","TATAELXSI",
    "TORNTPOWER","UPL","UBL","VOLTAS","YESBANK",
    # Smallcap F&O eligible
    "AAVAS","AARTIIND","ABFRL","AMBER","ANGELONE","BANDHANBNK","BATAINDIA","BLUEDART",
    "BRIGADE","CANFINHOME","CESC","CDSL","CAMS","CYIENT","DEEPAKNTR","DELHIVERY",
    "LALPATHLAB","EMAMILTD","FIVESTAR","FORCEMOT","GRANULES","HINDCOPPER","HOMEFIRST",
    "IGL","INDIAMART","IEX","JBCHEPHARM","J&KBANK","JINDALSAW","JUBLINGREA","JUBLPHARMA",
    "KARURVYSYA","KEI","KFINTECH","MANAPPURAM","NATCOPHARM","NBCC","NCC","NH","NAVINFLUOR",
    "PNBHOUSING","PVRINOX","RBLBANK","RADICO","REDINGTON","SAREGAMA","SCI","SOBHA",
    "SONACOMS","SYNGENE","TATACHEM","TIMKEN","TITAGARH","TRIDENT","UTIAMC","WELCORP",
    "WOCKPHARMA","ZEEL","ZENSARTECH",
]))


def get_symbols(index_names: list) -> list:
    """Return deduplicated NSE symbols for given index names."""
    symbols = []
    for name in index_names:
        symbols.extend(INDICES.get(name, []))
    return list(dict.fromkeys(symbols))


def get_yahoo_symbol(nse_symbol: str) -> str:
    return f"{nse_symbol}.NS"


INDEX_NAMES = list(INDICES.keys())