"""Static NSE symbol -> company name map for the curated universe.
Auto-generated from Yahoo chart meta (longName/shortName).
Regenerate with scratchpad/gen_names.py when indices.py changes.
Resolved 500/500 symbols.
"""

SYMBOL_NAMES = {
    "360ONE": "360 One Wam Limited",
    "3MINDIA": "3M India Limited",
    "AADHARHFC": "AADHAR HOUSING FINANCE L",
    "AARTIIND": "Aarti Industries Limited",
    "AAVAS": "Aavas Financiers Limited",
    "ABB": "ABB India Limited",
    "ABBOTINDIA": "Abbott India Limited",
    "ABCAPITAL": "Aditya Birla Capital Limited",
    "ABDL": "ALLIED BLEND N DISTILS L",
    "ABFRL": "Aditya Birla Fashion and Retail Limited",
    "ABLBL": "ADITYA BIRLA LIFES BRAN L",
    "ABREL": "Aditya Birla Real Estate Limited",
    "ABSLAMC": "Aditya Birla Sun Life AMC Limited",
    "ACC": "ACC Limited",
    "ACE": "Action Construction Equipment Limited",
    "ACMESOLAR": "ACME SOLAR HOLDINGS LTD",
    "ACUTAAS": "Acutaas Chemicals Limited",
    "ADANIENSOL": "Adani Energy Solutions Limited",
    "ADANIENT": "Adani Enterprises Limited",
    "ADANIGREEN": "Adani Green Energy Limited",
    "ADANIPORTS": "Adani Ports and Special Economic Zone Limited",
    "ADANIPOWER": "Adani Power Limited",
    "AEGISLOG": "AEGIS LOGISTICS LIMITED",
    "AEGISVOPAK": "AEGIS VOPAK TERMINALS LTD",
    "AFCONS": "AFCONS INFRASTRUCTURE LTD",
    "AFFLE": "Affle 3i Limited",
    "AIAENG": "AIA Engineering Limited",
    "AIIL": "Authum Investment & Infrastructure Limited",
    "AJANTPHARM": "Ajanta Pharma Limited",
    "ALKEM": "Alkem Laboratories Limited",
    "AMBER": "Amber Enterprises India Limited",
    "AMBUJACEM": "Ambuja Cements Limited",
    "ANANDRATHI": "Anand Rathi Wealth Limited",
    "ANANTRAJ": "Anant Raj Limited",
    "ANGELONE": "Angel One Limited",
    "ANTHEM": "ANTHEM BIOSCIENCES LTD",
    "ANURAS": "Anupam Rasayan India Ltd",
    "APARINDS": "APAR Industries Limited",
    "APLAPOLLO": "APL Apollo Tubes Limited",
    "APOLLOHOSP": "Apollo Hospitals Enterprise Limited",
    "APOLLOTYRE": "Apollo Tyres Limited",
    "APTUS": "Aptus Value Housing Finance India Limited",
    "ARE&M": "Amara Raja Energy & Mobility Limited",
    "ASAHIINDIA": "Asahi India Glass Limited",
    "ASHOKLEY": "Ashok Leyland Limited",
    "ASIANPAINT": "Asian Paints Limited",
    "ASTERDM": "Aster DM Healthcare Limited",
    "ASTRAL": "Astral Limited",
    "ATGL": "Adani Total Gas Limited",
    "ATHERENERG": "Ather Energy Limited",
    "ATUL": "Atul Ltd",
    "AUBANK": "AU Small Finance Bank Limited",
    "AUROPHARMA": "Aurobindo Pharma Limited",
    "AWL": "AWL Agri Business Limited",
    "AXISBANK": "Axis Bank Limited",
    "BAJAJ-AUTO": "Bajaj Auto Limited",
    "BAJAJFINSV": "Bajaj Finserv Ltd.",
    "BAJAJHFL": "BAJAJ HOUSING FINANCE LTD",
    "BAJAJHLDNG": "Bajaj Holdings & Investment Limited",
    "BAJFINANCE": "Bajaj Finance Limited",
    "BALKRISIND": "Balkrishna Industries Limited",
    "BALRAMCHIN": "Balrampur Chini Mills Limited",
    "BANDHANBNK": "Bandhan Bank Limited",
    "BANKBARODA": "Bank of Baroda Limited",
    "BANKINDIA": "Bank of India Limited",
    "BATAINDIA": "Bata India Limited",
    "BAYERCROP": "Bayer CropScience Limited",
    "BBTC": "The Bombay Burmah Trading Corporation Limited",
    "BDL": "Bharat Dynamics Limited",
    "BEL": "Bharat Electronics Limited",
    "BELRISE": "BELRISE INDUSTRIES LTD",
    "BEML": "BEML Limited",
    "BERGEPAINT": "Berger Paints India Limited",
    "BHARATFORG": "Bharat Forge Limited",
    "BHARTIARTL": "Bharti Airtel Limited",
    "BHARTIHEXA": "BHARTI HEXACOM LIMITED",
    "BHEL": "Bharat Heavy Electricals Limited",
    "BIKAJI": "Bikaji Foods International Limited",
    "BIOCON": "Biocon Limited",
    "BLS": "BLS International Services Limited",
    "BLUEDART": "Blue Dart Express Limited",
    "BLUEJET": "Blue Jet Healthcare Limited",
    "BLUESTARCO": "Blue Star Limited",
    "BOSCHLTD": "Bosch Limited",
    "BPCL": "Bharat Petroleum Corporation Limited",
    "BRIGADE": "Brigade Enterprises Limited",
    "BRITANNIA": "Britannia Industries Limited",
    "BSE": "BSE Limited",
    "BSOFT": "Birlasoft Limited",
    "CAMS": "Computer Age Management Services Limited",
    "CANBK": "Canara Bank",
    "CANFINHOME": "Can Fin Homes Limited",
    "CANHLIFE": "CANARA HSBC LIFE INS CO L",
    "CAPLIPOINT": "Caplin Point Laboratories Limited",
    "CARBORUNIV": "Carborundum Universal Limited",
    "CARTRADE": "CarTrade Tech Limited",
    "CASTROLIND": "Castrol India Limited",
    "CCL": "CCL Products (India) Limited",
    "CDSL": "Central Depository Services (India) Limited",
    "CEATLTD": "CEAT Limited",
    "CEMPRO": "Cemindia Projects Limited",
    "CENTRALBK": "Central Bank of India",
    "CESC": "CESC Limited",
    "CGCL": "Capri Global Capital Limited",
    "CGPOWER": "CG Power and Industrial Solutions Limited",
    "CHALET": "Chalet Hotels Limited",
    "CHAMBLFERT": "Chambal Fertilisers and Chemicals Limited",
    "CHENNPETRO": "Chennai Petroleum Corporation Limited",
    "CHOICEIN": "Choice International Limited",
    "CHOLAFIN": "Cholamandalam Investment and Finance Company Limited",
    "CHOLAHLDNG": "Cholamandalam Financial Holdings Limited",
    "CIEINDIA": "CIE Automotive India Limited",
    "CIPLA": "Cipla Limited",
    "CLEAN": "Clean Science and Technology Limited",
    "COALINDIA": "Coal India Limited",
    "COCHINSHIP": "Cochin Shipyard Limited",
    "COFORGE": "Coforge Limited",
    "COHANCE": "COHANCE LIFESCIENCES LTD",
    "COLPAL": "Colgate-Palmolive (India) Limited",
    "CONCOR": "Container Corporation of India Limited",
    "CONCORDBIO": "Concord Biotech Limited",
    "COROMANDEL": "Coromandel International Limited",
    "CPPLUS": "ADITYA INFOTECH LIMITED",
    "CRAFTSMAN": "Craftsman Automation Limited",
    "CREDITACC": "CreditAccess Grameen Limited",
    "CRISIL": "CRISIL Limited",
    "CROMPTON": "Crompton Greaves Consumer Electricals Limited",
    "CUB": "City Union Bank Limited",
    "CUMMINSIND": "Cummins India Limited",
    "CYIENT": "Cyient Limited",
    "DABUR": "Dabur India Limited",
    "DALBHARAT": "Dalmia Bharat Limited",
    "DATAPATTNS": "Data Patterns (India) Limited",
    "DCMSHRIRAM": "DCM Shriram Limited",
    "DEEPAKFERT": "Deepak Fertilisers And Petrochemicals Corporation Limited",
    "DEEPAKNTR": "Deepak Nitrite Limited",
    "DELHIVERY": "Delhivery Limited",
    "DEVYANI": "Devyani International Limited",
    "DIVISLAB": "Divi's Laboratories Limited",
    "DIXON": "Dixon Technologies (India) Limited",
    "DLF": "DLF Limited",
    "DMART": "Avenue Supermarts Limited",
    "DOMS": "DOMS Industries Limited",
    "DRREDDY": "Dr. Reddy's Laboratories Limited",
    "ECLERX": "eClerx Services Limited",
    "EICHERMOT": "Eicher Motors Limited",
    "EIDPARRY": "E.I.D.- Parry (India) Limited",
    "EIHOTEL": "EIH Limited",
    "ELECON": "Elecon Engineering Company Limited",
    "ELGIEQUIP": "Elgi Equipments Limited",
    "EMAMILTD": "Emami Limited",
    "EMCURE": "EMCURE PHARMACEUTICALS L",
    "EMMVEE": "EMMVEE PHOTOVOLTAIC PWR L",
    "ENDURANCE": "Endurance Technologies Limited",
    "ENGINERSIN": "Engineers India Limited",
    "ENRIN": "Siemens Energy India Limited",
    "ERIS": "Eris Lifesciences Limited",
    "ESCORTS": "Escorts Kubota Limited",
    "ETERNAL": "Eternal Limited",
    "EXIDEIND": "Exide Industries Limited",
    "FACT": "The Fertilisers and Chemicals Travancore Limited",
    "FEDERALBNK": "The Federal Bank Limited",
    "FINCABLES": "Finolex Cables Limited",
    "FIRSTCRY": "BRAINBEES SOLUTIONS LTD",
    "FIVESTAR": "Five-Star Business Finance Limited",
    "FLUOROCHEM": "Gujarat Fluorochemicals Limited",
    "FORCEMOT": "Force Motors Limited",
    "FORTIS": "Fortis Healthcare Limited",
    "FSL": "Firstsource Solutions Limited",
    "GABRIEL": "Gabriel India Limited",
    "GAIL": "GAIL (India) Limited",
    "GALLANTT": "Gallantt Ispat Limited",
    "GESHIP": "The Great Eastern Shipping Company Limited",
    "GICRE": "General Insurance Corporation of India",
    "GILLETTE": "Gillette India Limited",
    "GLAND": "Gland Pharma Limited",
    "GLAXO": "GlaxoSmithKline Pharmaceuticals Limited",
    "GLENMARK": "Glenmark Pharmaceuticals Limited",
    "GMDCLTD": "Gujarat Mineral Development Corporation Limited",
    "GMRAIRPORT": "GMR Airports Limited",
    "GODFRYPHLP": "Godfrey Phillips India Limited",
    "GODIGIT": "GO DIGIT GENERAL INS LTD",
    "GODREJCP": "Godrej Consumer Products Limited",
    "GODREJIND": "Godrej Industries Limited",
    "GODREJPROP": "Godrej Properties Limited",
    "GPIL": "Godawari Power & Ispat Limited",
    "GRANULES": "Granules India Limited",
    "GRAPHITE": "Graphite India Limited",
    "GRASIM": "Grasim Industries Limited",
    "GRAVITA": "Gravita India Limited",
    "GROWW": "BILLIONBRAINS GARAGE VN L",
    "GRSE": "Garden Reach Shipbuilders & Engineers Limited",
    "GVT&D": "GE Vernova T&D India Ltd",
    "HAL": "Hindustan Aeronautics Limited",
    "HAVELLS": "Havells India Limited",
    "HBLENGINE": "HBL ENGINEERING LTD",
    "HCLTECH": "HCL Technologies Limited",
    "HDBFS": "HDB FINANCIAL SERVICES L",
    "HDFCAMC": "HDFC Asset Management Company Limited",
    "HDFCBANK": "HDFC Bank Limited",
    "HDFCLIFE": "HDFC Life Insurance Company Limited",
    "HEG": "HEG Limited",
    "HEROMOTOCO": "Hero MotoCorp Limited",
    "HEXT": "Hexaware Technologies Limited",
    "HFCL": "HFCL Limited",
    "HINDALCO": "Hindalco Industries Limited",
    "HINDCOPPER": "Hindustan Copper Limited",
    "HINDPETRO": "Hindustan Petroleum Corporation Limited",
    "HINDUNILVR": "Hindustan Unilever Limited",
    "HINDZINC": "Hindustan Zinc Limited",
    "HOMEFIRST": "Home First Finance Company India Limited",
    "HONASA": "Honasa Consumer Limited",
    "HONAUT": "Honeywell Automation India Limited",
    "HSCL": "Himadri Speciality Chemical Limited",
    "HUDCO": "Housing and Urban Development Corporation Limited",
    "HYUNDAI": "HYUNDAI MOTOR INDIA LTD",
    "ICICIAMC": "ICICI PRUDENTIAL AMC LTD",
    "ICICIBANK": "ICICI Bank Limited",
    "ICICIGI": "ICICI Lombard General Insurance Company Limited",
    "ICICIPRULI": "ICICI Prudential Life Insurance Company Limited",
    "IDBI": "IDBI Bank Limited",
    "IDEA": "Vodafone Idea Limited",
    "IDFCFIRSTB": "IDFC First Bank Limited",
    "IEX": "Indian Energy Exchange Limited",
    "IFCI": "IFCI Limited",
    "IGIL": "International Gemological Institute Limited",
    "IGL": "Indraprastha Gas Limited",
    "IIFL": "IIFL Finance Limited",
    "IKS": "INVENTURUS KNOWLEDGE SO L",
    "INDGN": "INDEGENE LIMITED",
    "INDHOTEL": "The Indian Hotels Company Limited",
    "INDIACEM": "The India Cements Limited",
    "INDIAMART": "IndiaMART InterMESH Limited",
    "INDIANB": "Indian Bank",
    "INDIGO": "InterGlobe Aviation Limited",
    "INDUSINDBK": "IndusInd Bank Limited",
    "INDUSTOWER": "Indus Towers Limited",
    "INFY": "Infosys Limited",
    "INOXWIND": "Inox Wind Limited",
    "INTELLECT": "Intellect Design Arena Limited",
    "IOB": "Indian Overseas Bank",
    "IOC": "Indian Oil Corporation Limited",
    "IPCALAB": "Ipca Laboratories Limited",
    "IRB": "IRB Infrastructure Developers Limited",
    "IRCON": "Ircon International Limited",
    "IRCTC": "Indian Railway Catering & Tourism Corporation Limited",
    "IREDA": "Indian Renewable Energy Development Agency Limited",
    "IRFC": "Indian Railway Finance Corporation Limited",
    "ITC": "ITC Limited",
    "ITCHOTELS": "ITC HOTELS LIMITED",
    "ITI": "ITI Limited",
    "J&KBANK": "Jammu and Kashmir Bank Limited",
    "JAINREC": "JAIN RESOURCE RECYCLING L",
    "JBCHEPHARM": "J. B. Chemicals & Pharmaceuticals Limited",
    "JBMA": "JBM Auto Limited",
    "JINDALSAW": "Jindal Saw Limited",
    "JINDALSTEL": "Jindal Steel Limited",
    "JIOFIN": "Jio Financial Services Limited",
    "JKCEMENT": "J.K. Cement Limited",
    "JKTYRE": "JK Tyre & Industries Limited",
    "JMFINANCIL": "JM Financial Limited",
    "JPPOWER": "Jaiprakash Power Ventures Limited",
    "JSL": "Jindal Stainless Limited",
    "JSWCEMENT": "JSW CEMENT LIMITED",
    "JSWDULUX": "JSW Dulux Limited",
    "JSWENERGY": "JSW Energy Limited",
    "JSWINFRA": "JSW Infrastructure Limited",
    "JSWSTEEL": "JSW Steel Limited",
    "JUBLFOOD": "Jubilant FoodWorks Limited",
    "JUBLINGREA": "Jubilant Ingrevia Limited",
    "JUBLPHARMA": "Jubilant Pharmova Limited",
    "JWL": "Jupiter Wagons Limited",
    "JYOTICNC": "Jyoti CNC Automation Limited",
    "KAJARIACER": "Kajaria Ceramics Limited",
    "KALYANKJIL": "Kalyan Jewellers India Limited",
    "KARURVYSYA": "The Karur Vysya Bank Limited",
    "KAYNES": "Kaynes Technology India Limited",
    "KEC": "KEC International Limited",
    "KEI": "KEI Industries Limited",
    "KFINTECH": "KFin Technologies Limited",
    "KIMS": "Krishna Institute of Medical Sciences Limited",
    "KIRLOSENG": "Kirloskar Oil Engines Limited",
    "KOTAKBANK": "Kotak Mahindra Bank Limited",
    "KPIL": "Kalpataru Projects International Limited",
    "KPITTECH": "KPIT Technologies Limited",
    "KPRMILL": "K.P.R. Mill Limited",
    "LALPATHLAB": "Dr. Lal PathLabs Limited",
    "LATENTVIEW": "Latent View Analytics Limited",
    "LAURUSLABS": "Laurus Labs Limited",
    "LEMONTREE": "Lemon Tree Hotels Limited",
    "LENSKART": "LENSKART SOLUTIONS LTD",
    "LGEINDIA": "LG ELECTRONICS INDIA LTD",
    "LICHSGFIN": "LIC Housing Finance Limited",
    "LICI": "Life Insurance Corporation of India",
    "LINDEINDIA": "Linde India Limited",
    "LLOYDSME": "Lloyds Metals and Energy Limited",
    "LODHA": "Lodha Developers Limited",
    "LT": "Larsen & Toubro Limited",
    "LTF": "L&T Finance Limited",
    "LTFOODS": "LT Foods Limited",
    "LTM": "LTM Limited",
    "LTTS": "L&T Technology Services Limited",
    "LUPIN": "Lupin Limited",
    "M&M": "Mahindra & Mahindra Limited",
    "M&MFIN": "Mahindra & Mahindra Financial Services Limited",
    "MAHABANK": "Bank of Maharashtra",
    "MANAPPURAM": "Manappuram Finance Limited",
    "MANKIND": "Mankind Pharma Limited",
    "MAPMYINDIA": "C. E. Info Systems Limited",
    "MARICO": "Marico Limited",
    "MARUTI": "Maruti Suzuki India Limited",
    "MAXHEALTH": "Max Healthcare Institute Limited",
    "MAZDOCK": "Mazagon Dock Shipbuilders Limited",
    "MCX": "Multi Commodity Exchange of India Limited",
    "MEDANTA": "Global Health Limited",
    "MEESHO": "MEESHO LIMITED",
    "MFSL": "Max Financial Services Limited",
    "MGL": "Mahanagar Gas Limited",
    "MINDACORP": "Minda Corporation Limited",
    "MMTC": "MMTC Limited",
    "MOTHERSON": "Samvardhana Motherson International Limited",
    "MOTILALOFS": "Motilal Oswal Financial Services Limited",
    "MPHASIS": "Mphasis Limited",
    "MRF": "MRF Limited",
    "MRPL": "Mangalore Refinery and Petrochemicals Limited",
    "MSUMI": "Motherson Sumi Wiring India Limited",
    "MUTHOOTFIN": "Muthoot Finance Limited",
    "NAM-INDIA": "Nippon Life India Asset Management Limited",
    "NATCOPHARM": "NATCO Pharma Limited",
    "NATIONALUM": "National Aluminium Company Limited",
    "NAUKRI": "Info Edge (India) Limited",
    "NAVA": "Nava Limited",
    "NAVINFLUOR": "Navin Fluorine International Limited",
    "NBCC": "NBCC (India) Limited",
    "NCC": "NCC Limited",
    "NESTLEIND": "Nestl\u00e9 India Limited",
    "NETWEB": "Netweb Technologies India Limited",
    "NEULANDLAB": "Neuland Laboratories Limited",
    "NEWGEN": "Newgen Software Technologies Limited",
    "NH": "Narayana Hrudayalaya Limited",
    "NHPC": "NHPC Limited",
    "NIACL": "The New India Assurance Company Limited",
    "NIVABUPA": "Niva Bupa Health Insurance Company Limited",
    "NLCINDIA": "NLC India Limited",
    "NMDC": "NMDC Limited",
    "NSLNISP": "NMDC Steel Limited",
    "NTPC": "NTPC Limited",
    "NTPCGREEN": "NTPC GREEN ENERGY LIMITED",
    "NUVAMA": "Nuvama Wealth Management Limited",
    "NUVOCO": "Nuvoco Vistas Corporation Limited",
    "NYKAA": "FSN E-Commerce Ventures Limited",
    "OBEROIRLTY": "Oberoi Realty Limited",
    "OFSS": "Oracle Financial Services Software Limited",
    "OIL": "Oil India Limited",
    "OLAELEC": "OLA ELECTRIC MOBILITY LTD",
    "OLECTRA": "Olectra Greentech Limited",
    "ONESOURCE": "ONESOURCE SPECL PHARMA L",
    "ONGC": "Oil and Natural Gas Corporation Limited",
    "PAGEIND": "Page Industries Limited",
    "PARADEEP": "Paradeep Phosphates Limited",
    "PATANJALI": "Patanjali Foods Limited",
    "PAYTM": "One97 Communications Limited",
    "PCBL": "PCBL Chemical Limited",
    "PERSISTENT": "Persistent Systems Limited",
    "PETRONET": "Petronet LNG Limited",
    "PFC": "Power Finance Corporation Limited",
    "PFIZER": "Pfizer Limited",
    "PGEL": "PG Electroplast Limited",
    "PHOENIXLTD": "The Phoenix Mills Limited",
    "PIDILITIND": "Pidilite Industries Limited",
    "PIIND": "PI Industries Limited",
    "PINELABS": "PINE LABS LIMITED",
    "PIRAMALFIN": "PIRAMAL FINANCE LIMITED",
    "PNB": "Punjab National Bank",
    "PNBHOUSING": "PNB Housing Finance Limited",
    "POLICYBZR": "PB Fintech Limited",
    "POLYCAB": "Polycab India Limited",
    "POLYMED": "Poly Medicure Limited",
    "POONAWALLA": "Poonawalla Fincorp Limited",
    "POWERGRID": "Power Grid Corporation of India Limited",
    "POWERINDIA": "Hitachi Energy India Limited",
    "PPLPHARMA": "Piramal Pharma Limited",
    "PREMIERENE": "PREMIER ENERGIES LIMITED",
    "PRESTIGE": "Prestige Estates Projects Limited",
    "PTCIL": "PTC Industries Limited",
    "PVRINOX": "PVR INOX Limited",
    "PWL": "Physicswallah Limited",
    "RADICO": "Radico Khaitan Limited",
    "RAILTEL": "RailTel Corporation of India Limited",
    "RAINBOW": "Rainbow Children's Medicare Limited",
    "RAMCOCEM": "The Ramco Cements Limited",
    "RBLBANK": "RBL Bank Limited",
    "RECLTD": "REC Limited",
    "REDINGTON": "Redington Limited",
    "RELIANCE": "Reliance Industries Limited",
    "RHIM": "RHI Magnesita India Limited",
    "RITES": "RITES Limited",
    "RKFORGE": "Ramkrishna Forgings Limited",
    "RPOWER": "Reliance Power Limited",
    "RRKABEL": "R R Kabel Limited",
    "RVNL": "Rail Vikas Nigam Limited",
    "SAGILITY": "Sagility Limited",
    "SAIL": "Steel Authority of India Limited",
    "SAILIFE": "SAI LIFE SCIENCES LIMITED",
    "SAMMAANCAP": "Sammaan Capital Limited",
    "SAPPHIRE": "Sapphire Foods India Limited",
    "SARDAEN": "Sarda Energy & Minerals Limited",
    "SAREGAMA": "Saregama India Limited",
    "SBFC": "SBFC Finance Limited",
    "SBICARD": "SBI Cards and Payment Services Limited",
    "SBILIFE": "SBI Life Insurance Company Limited",
    "SBIN": "State Bank of India",
    "SCHAEFFLER": "Schaeffler India Limited",
    "SCHNEIDER": "Schneider Electric Infrastructure Limited",
    "SCI": "The Shipping Corporation of India Limited",
    "SHREECEM": "Shree Cement Limited",
    "SHRIRAMFIN": "Shriram Finance Limited",
    "SHYAMMETL": "Shyam Metalics and Energy Limited",
    "SIEMENS": "Siemens Limited",
    "SIGNATURE": "Signatureglobal (India) Limited",
    "SJVN": "SJVN Limited",
    "SOBHA": "Sobha Limited",
    "SOLARINDS": "Solar Industries India Limited",
    "SONACOMS": "Sona BLW Precision Forgings Limited",
    "SONATSOFTW": "Sonata Software Limited",
    "SPLPETRO": "Supreme Petrochem Limited",
    "SRF": "SRF Limited",
    "STARHEALTH": "Star Health and Allied Insurance Company Limited",
    "SUMICHEM": "Sumitomo Chemical India Limited",
    "SUNDARMFIN": "Sundaram Finance Limited",
    "SUNPHARMA": "Sun Pharmaceutical Industries Limited",
    "SUNTV": "Sun TV Network Limited",
    "SUPREMEIND": "The Supreme Industries Limited",
    "SUZLON": "Suzlon Energy Limited",
    "SWANCORP": "Swan Corp Limited",
    "SWIGGY": "SWIGGY LIMITED",
    "SYNGENE": "Syngene International Limited",
    "SYRMA": "Syrma SGS Technology Limited",
    "TARIL": "TRANS & RECTI. LTD",
    "TATACAP": "TATA CAPITAL LIMITED",
    "TATACHEM": "Tata Chemicals Limited",
    "TATACOMM": "Tata Communications Limited",
    "TATACONSUM": "Tata Consumer Products Limited",
    "TATAELXSI": "Tata Elxsi Limited",
    "TATAINVEST": "Tata Investment Corporation Limited",
    "TATAPOWER": "The Tata Power Company Limited",
    "TATASTEEL": "Tata Steel Limited",
    "TATATECH": "Tata Technologies Limited",
    "TBOTEK": "TBO TEK LIMITED",
    "TCS": "Tata Consultancy Services Limited",
    "TECHM": "Tech Mahindra Limited",
    "TECHNOE": "Techno Electric & Engineering Company Limited",
    "TEGA": "Tega Industries Limited",
    "TEJASNET": "Tejas Networks Limited",
    "TENNIND": "TENNECO CLEAN AIR INDIA L",
    "THELEELA": "Leela Palaces Hotels & Resorts Limited",
    "THERMAX": "Thermax Limited",
    "TIINDIA": "Tube Investments of India Limited",
    "TIMKEN": "Timken India Limited",
    "TITAGARH": "Titagarh Rail Systems Limited",
    "TITAN": "Titan Company Limited",
    "TMCV": "TATA MOTORS LIMITED",
    "TMPV": "Tata Motors Passenger Vehicles Limited",
    "TORNTPHARM": "Torrent Pharmaceuticals Limited",
    "TORNTPOWER": "Torrent Power Limited",
    "TRAVELFOOD": "TRAVEL FOOD SERVICES LTD",
    "TRENT": "Trent Limited",
    "TRIDENT": "Trident Limited",
    "TRITURBINE": "Triveni Turbine Limited",
    "TTML": "Tata Teleservices (Maharashtra) Limited",
    "TVSMOTOR": "TVS Motor Company Limited",
    "UBL": "United Breweries Limited",
    "UCOBANK": "UCO Bank",
    "ULTRACEMCO": "UltraTech Cement Limited",
    "UNIONBANK": "Union Bank of India",
    "UNITDSPR": "UNITED SPIRITS LIMITED",
    "UNOMINDA": "Uno Minda Limited",
    "UPL": "UPL Limited",
    "URBANCO": "Urban Company Limited",
    "USHAMART": "Usha Martin Limited",
    "UTIAMC": "UTI Asset Management Company Limited",
    "VBL": "Varun Beverages Limited",
    "VEDL": "Vedanta Limited",
    "VIJAYA": "Vijaya Diagnostic Centre Limited",
    "VMM": "VISHAL MEGA MART LIMITED",
    "VOLTAS": "Voltas Limited",
    "VTL": "Vardhman Textiles Limited",
    "WAAREEENER": "WAAREE ENERGIES LIMITED",
    "WELCORP": "Welspun Corp Limited",
    "WELSPUNLIV": "Welspun Living Limited",
    "WHIRLPOOL": "Whirlpool of India Limited",
    "WIPRO": "Wipro Limited",
    "WOCKPHARMA": "Wockhardt Limited",
    "YESBANK": "Yes Bank Limited",
    "ZEEL": "Zee Entertainment Enterprises Limited",
    "ZENSARTECH": "Zensar Technologies Limited",
    "ZENTEC": "Zen Technologies Limited",
    "ZFCVINDIA": "ZF Commercial Vehicle Control Systems India Limited",
    "ZYDUSLIFE": "Zydus Lifesciences Limited",
    "ZYDUSWELL": "Zydus Wellness Limited",
}
